### ISSUE TITLE
did configuration, rename `domain` to `origin`

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/.well-known#34]
- [x] Update Spec
- [ ] Update Demos

**Comment by tplooker** [comment]
Can we get some rationale for this change I was unable to attend the I&D call this morning where this topic was apparently spoken about?

**Comment by peacekeeper** [comment]
@tplooker my recollection of the discussion is that "domain" isn't completely accurate. Strictly speaking, this is not about linking a domain name to a DID, but about linking a web address or http URL to a DID. There was a lot of discussion on the call on what it means to "control a domain name". A domain name has Business, Technical, and Billing contacts, who could have the power to "control" the domain name. But in the case of DID configuration, it's also the web administrator who "controls" the link, since they can upload the file to the .well-known/ location.

We worked on a way to link directly from DNS to DIDs a while ago: https://datatracker.ietf.org/doc/draft-mayrhofer-did-dns/, but this is of course less practical than uploading a file to a webserver, and it hasn't seen any adoption.

In practical terms, this difference may not matter much. For example, the organization who "controls" the domain name "microsoft.com" also controls the web address "https://microsoft.com/.well-known", so in this case the difference may not matter.

Also, there was some discussion about subdomains.. If you control "microsoft.com", does that mean all the subdomains are controlled by the same organization, or could subdomains have different "controllers" (and therefore link to different DIDs)?

So for these reasons, "origin" was suggested as a better fit. @csuwildcat and @dhh1128 were quite active in the discussion, maybe they want to add more thoughts.

**Comment by peacekeeper** [comment]
One thing I don't understand is why the spec uses did:web examples. What's the point of linking from a domain name (origin) to a did:web based on the same domain name? Wouldn't a better example use another DID method such as did:key, did:elem, etc..?

**Comment by OR13** [comment]
@peacekeeper absolutely... did web is just the easiest did method to control. better examples / tests  / PRs welcome.

**Comment by csuwildcat** [comment]
I changed the property and some terminology to include `origin` in the merged PR, but think we should leave the title of the spec and domain descriptive language in many areas, because when paired with origin language, it helps people understand the difference between web origins and domains (the former is rather arcane, so the latter helps ground it).

**Comment by jmandel** [comment]
The current spec uses the term `origin` and even links to https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy for explanation -- but the values supplied are *not* origins, but rather bare domain names. This is confusing (and has already led to compatibility problems in testing).

**Comment by OR13** [comment]
we did this.
